# Generated by Django 3.2.13 on 2022-12-01 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogroup',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
