# Generated by Django 3.2.13 on 2022-11-29 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '__first__'),
        ('walkings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mylotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dogroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField()),
                ('title', models.CharField(max_length=20)),
                ('membercnt', models.IntegerField(default=5)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dog')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkings.park')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
