# Generated by Django 3.2.13 on 2022-12-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('walkings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogroup',
            name='dog',
        ),
        migrations.AddField(
            model_name='dogroup',
            name='dogs',
            field=models.ManyToManyField(related_name='joindogs', to='accounts.Dog'),
        ),
    ]
