# Generated by Django 3.2.13 on 2022-12-01 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walkings', '0002_alter_dogroup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogroup',
            name='join',
            field=models.ManyToManyField(related_name='joiner', to=settings.AUTH_USER_MODEL),
        ),
    ]
