# Generated by Django 3.2.13 on 2022-12-08 02:51

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dogphoto',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='static/images/입양.png/', upload_to='images/dogphoto/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='neutered',
            field=models.CharField(choices=[('O', 'O'), ('X', 'X'), ('?', '?')], max_length=255),
        ),
    ]
