# Generated by Django 3.2.13 on 2022-12-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='neutered',
            field=models.CharField(choices=[('O', 'O'), ('X', 'X'), ('?', '?')], max_length=255),
        ),
    ]
