# Generated by Django 3.2.13 on 2022-12-07 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221204_0656'),
        ('accounts', '0002_auto_20221206_1043'),
    ]

    operations = [
    ]
