# Generated by Django 3.2.13 on 2022-12-06 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PetPlaceSlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideimage', models.CharField(max_length=200)),
                ('petplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slideimage', to='info.petplace')),
            ],
        ),
        migrations.CreateModel(
            name='PetPlaceBodyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyimage', models.CharField(max_length=200)),
                ('petplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodyimage', to='info.petplace')),
            ],
        ),
    ]
