# Generated by Django 3.2.13 on 2022-12-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_petplace_petplacebodyimage_petplaceslideimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='petplace',
            name='imageURL',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
